// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type TopicsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/topics/controller/topics_controller.ts').default['render'], false>
}
type TopicsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/topics/controller/topics_controller.ts').default['show'], false>
}
type SeriesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/series/controller/series_controller.ts').default['render'], false>
}
type BlogGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/blog/controller/blog_controller.ts').default['render'], false>
}
type BlogIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/blog/controller/blog_controller.ts').default['render'], false>
}
export interface ApiDefinition {
  'topics': {
    '$url': {
    };
    '$get': TopicsGetHead;
    '$head': TopicsGetHead;
    ':slug': {
      '$url': {
      };
      '$get': TopicsIdGetHead;
      '$head': TopicsIdGetHead;
    };
  };
  'series': {
    '$url': {
    };
    '$get': SeriesGetHead;
    '$head': SeriesGetHead;
  };
  'blog': {
    '$url': {
    };
    '$get': BlogGetHead;
    '$head': BlogGetHead;
    ':slug': {
      '$url': {
      };
      '$get': BlogIdGetHead;
      '$head': BlogIdGetHead;
    };
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["*"],
    name: 'img',
    path: '/img/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'home',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'topics.index',
    path: '/topics',
    method: ["GET","HEAD"],
    types: {} as TopicsGetHead,
  },
  {
    params: ["slug"],
    name: 'topics.show',
    path: '/topics/:slug',
    method: ["GET","HEAD"],
    types: {} as TopicsIdGetHead,
  },
  {
    params: [],
    name: 'series.index',
    path: '/series',
    method: ["GET","HEAD"],
    types: {} as SeriesGetHead,
  },
  {
    params: [],
    name: 'lessons.index',
    path: '/lessons',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["slug"],
    name: 'lessons.show',
    path: '/lessons/:slug',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'blog.index',
    path: '/blog',
    method: ["GET","HEAD"],
    types: {} as BlogGetHead,
  },
  {
    params: ["slug"],
    name: 'blog.show',
    path: '/blog/:slug',
    method: ["GET","HEAD"],
    types: {} as BlogIdGetHead,
  },
  {
    params: [],
    name: 'comments.store',
    path: '/comment',
    method: ["POST"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
