// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type LoginGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/login_controller.ts').default['show'], false>
}
type LoginPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/login_controller.ts').default['execute'], false>
}
type SeriesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/series/controller/series_controller.ts').default['render'], false>
}
export interface ApiDefinition {
  'login': {
    '$url': {
    };
    '$get': LoginGetHead;
    '$head': LoginGetHead;
    '$post': LoginPost;
  };
  'series': {
    '$url': {
    };
    '$get': SeriesGetHead;
    '$head': SeriesGetHead;
  };
}
const routes = [
  {
    params: [],
    name: 'admin.pages.dashboard',
    path: '/admin/dashboard',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'admin.articles.index',
    path: '/admin/articles',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'admin.article.create',
    path: '/admin/articles/create',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'admin.articles.store',
    path: '/admin/articles',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'admin.articles.edit',
    path: '/admin/articles/:id/edit',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'admin.articles.update',
    path: '/admin/articles/:id',
    method: ["PUT"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'admin.pages.users',
    path: '/admin/users',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'admin.pages.blogs',
    path: '/admin/views',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'home',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'login_route_show',
    path: '/login',
    method: ["GET","HEAD"],
    types: {} as LoginGetHead,
  },
  {
    params: [],
    name: 'login_route',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'topics.index',
    path: '/topics',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["slug"],
    name: 'topics.show',
    path: '/topics/:slug',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'series.index',
    path: '/series',
    method: ["GET","HEAD"],
    types: {} as SeriesGetHead,
  },
  {
    params: [],
    name: 'comments.store',
    path: '/comment',
    method: ["POST"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
