local:
  hosts:
    192.168.1.66:
      ansible_user: dev
      self_signed: yes
      ansible_ssh_private_key_file: '~/.ssh/id_ed25519'
      ansible_ssh_port: 2222
      root_path: '/home/{{ ansible_user }}/dev.com'
      ansible_python_interpreter: /usr/bin/python3

remote:
  hosts:
    eembouz.com:
      database: postgres
      database_password: password
      ansible_user: eembouz
      ansible_ssh_private_key_file: '~/.ssh/eembouz/eembouz'
      domain: eembouz.com
      self_signed: yes
      root_path: '/home/{{ ansible_user }}/eembouz.com'
      ansible_python_interpreter: /usr/bin/python3
