// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

export interface ApiDefinition {
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'auth.login.show',
    path: '/login',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'auth.login.store',
    path: '/login',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/logout',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["*"],
    name: 'assets.show',
    path: '/assets/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'assets.destroy',
    path: '/assets/:id',
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["typeId"],
    name: 'assets.store',
    path: '/assets/:typeId?',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'dashboard',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'articles.index',
    path: '/articles',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'articles.create',
    path: '/articles/create',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'articles.store',
    path: '/articles',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'articles.edit',
    path: '/articles/:id',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'articles.update',
    path: '/articles/:id',
    method: ["PUT"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'articles.destroy',
    path: '/articles/:id',
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'taxonomies.index',
    path: '/taxonomies',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'taxonomies.create',
    path: '/taxonomies/create',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'taxonomies.store',
    path: '/taxonomies',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'taxonomies.edit',
    path: '/taxonomies/:id',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'taxonomies.update',
    path: '/taxonomies/:id',
    method: ["PUT"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'taxonomies.destroy',
    path: '/taxonomies/:id',
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'collections.index',
    path: '/collections',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
